{% set name = "kedro-airflow" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3e0d9832ba41e17f5255e8ac1fb0d12b05d38d96d7af3184c86d0bcd443dcc50

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - setuptools >=61.2
    - python >=3.8
  run:
    - kedro >=0.19.0
    - python >=3.8
    - python-slugify >=4.0
    - semver >=2.10.0

test:
  imports:
    - kedro_airflow
  commands:
    - pip check
    # Note kedro-airflow 0.5.1 has requirement semver~=2.10, but you have semver 3.0.1
    # Note kedro 0.18.11 has requirement pip-tools~=6.5, but you have pip-tools 7.1.0
  requires:
    - pip

about:
  home: https://github.com/kedro-org/kedro-plugins/tree/main/kedro-airflow
  summary: Kedro-Airflow makes it easy to deploy Kedro projects to Airflow
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - cshaley
    - rxm7706
    - millsks
    - elanqo
    - zaigner
