{% set name = "kedro-airflow" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5d22a8797a49bf0633885ddc49bef7fc8db2d98c2e5cbe80ec5655dc8c5bce50

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.2
  run:
    - python >={{ python_min }}
    - kedro >=0.19.0
    - python-slugify >=4.0
    - semver >=2.10.0

test:
  imports:
    - kedro_airflow
  commands:
    - pip check
    # Note kedro-airflow 0.5.1 has requirement semver~=2.10, but you have semver 3.0.1
    # Note kedro 0.18.11 has requirement pip-tools~=6.5, but you have pip-tools 7.1.0
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/kedro-org/kedro-plugins/tree/main/kedro-airflow
  summary: Kedro-Airflow makes it easy to deploy Kedro projects to Airflow
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - cshaley
    - rxm7706
    - millsks
    - elanqo
    - zaigner
